Item.create!([
  {name: "Vintner's Daughter", price: "180.0", description: "Active Botanical Serum is a 100% active face oil, strategically formulated to have the multi-correctional activity and penetration of a super-powered serum. Made from the world’s most nutrient rich botanicals and essential oils, it is a skincare game changer that restores skin’s balance, texture and natural radiance.", picture: "vintners-daughter.jpg"},
  {name: "Rose Gold Safety Razor", price: "75.0", description: "What does shaving look like when it's made for women? This. A blade engineered to be irritation free. A tool that's balanced and weighted to make shaving a pleasure. A safety razor that is built to last. This is for curves and angles. This is for the girls who want to show up for their lives- minus the razor burn. We've got you, and your legs, covered.", picture: "oui-shave-razor.jpg"},
  {name: "Anti-Pollution Hydra Defense Mist", price: "28.0", description: "Shields against city living, pollution and external aggressors, and protects, hydrates and detoxifies skin at the same time.", picture: "patyka-hydra-defense-anti-pollution-mist.jpg"},
  {name: "Dry Shampoo With Oatmilk", price: "20.0", description: "An award-winning dry shampoo that cleans hair, eliminates oil and adds volume and texture to hair with ultra-gentle botanical ingredients.", picture: "oatmilk-dry-shampoo.png"},
  {name: "Rose Hibiscus Hydrating Face Mist", price: "32.0", description: "Rose Hibiscus Hydrating Face Mist is created with pure plant actives — no fillers. A base of coconut water is infused with youth-boosting hibiscus flower petals and moisture-enhancing rose to tone, hydrate, and soften all skin types.", picture: "rose-hibiscus.jpg"},
  {name: "Coconut Milk Bath Soak", price: "18.0", description: "Deeply hydrating coconut milk is the basis of this skin softening and soothing soak. Consisting of only four natural ingredients. Leaves skin hydrated and silky soft with a light scent of natural coconut and vanilla.", picture: "coconut-bath.jpg"},
  {name: "Jasmine Body Oil", price: "44.0", description: "Named for the precious Jasmine Sambac oil that it contains, the Jasmine Body Oil is a blend of pure, natural botanical oils that leave skin glowing and hydrated with an intoxicating floral scent.", picture: "jasmine-oil.jpg"},
  {name: "Small Mantra Candle - 4 oz Soy", price: "35.0", description: "Ria Ray's small hand-poured soy candles promote calm and well-being. Each one symbolizes a significant quality of life. Beautiful alone or together. Create a community of your favorite equations and scents by mixing any of the three scent + mantra combinations.\n\nstrength + truth = power: sandalwood, sage, rose\n\nlight + intimacy = love: blood orange, tangerine, guava\n\nsacred + humility = grace: bamboo, cassis, jasmine petals", picture: "small-candle.png"},
  {name: "Boundless Solid Oil", price: "88.0", description: "Containing powerful antioxidants, vitamins, minerals and a rich source of essential fatty acids, Amla is the most antioxidant rich ingredient in the world.", picture: "8-faces.jpg"},
  {name: "Divine Neroli Body Wash", price: "35.0", description: "Citrusy and zesty Divine Neroli Body Wash leaves skin delicately scented and soothes the body and soul.\n\n", picture: "neroli-wash.png"},
  {name: "Mokara Candle", price: "30.0", description: "Mokara: Notes of Mokara Orchid, White Lily, Spring Moss. Our classic embossed glass jar design and proprietary coconut wax blend get an update with discerning Japanese inspiration. Beautiful hues glimmer as the flame illuminates delicate embossing. You’ll love using the jar for jewelry, flowers or decor long after the candle is gone. Burn time is approximately 100 hours.", picture: "mokara.jpg"},
  {name: "Shave Creme", price: "32.0", description: "You + your razor. It hasn’t always been #relationshipgoals. It’s time to smooth things over with a better shave lotion. This powerful shaving cream for women is a trio of argan, coconut, and grapeseed oils moisturizes and primes skin for your best shave yet, while calendula and chamomile help to soothe and heal the skin. With Blood Orange and Jasmine essential oils, we can only describe the scent as so much #yass", picture: "shave-creme.jpg"},
  {name: "Rejuvenating Face Serum", price: "95.0", description: "Mālayā Organics Rejuvenating Face Serum is an extraordinary blend of 26 active botanical ingredients in a lightweight, deeply hydrating, vitamin-rich formula. Anti-inflammatory and Lenoleic Acid rich Siberian Cedar Nut Oil coupled with Gardenia Absolute’s antioxidant and collagen-synthesizing properties nourish skin, keeping it healthy and balanced. This harmonious fusion of bioactive essences, solar charged herbal extracts and nourishing omega fatty acid rich oils quickly absorb into skin, helping maintain and replenish moisture levels and restore skin’s elasticity. Teeming with ingredients rich in vitamins, minerals, and phytonutrients, this 100% natural elixir is both youth promoting and suitable for problematic skin.", picture: "malaya.jpg"},
  {name: "Aventurine Kiss Lip Serum", price: "44.0", description: "A triple-action serum formulated to help restore lips’ natural plumpness, deliver vital hydration and address the vertical lines of the lip area.", picture: "lip-serum.png"},
  {name: "Lady Suite Botanical Oil", price: "46.0", description: "A highly rejuvenating blend of organic and natural botanical oils thoughtfully created for your most delicate, intimate skin as a calming, revitalizing + illuminating oil for beautiful (and often temperamental) lady parts.", picture: "lady-business.jpeg"},
  {name: "Lux Aestiva Bambino Boheme Crystals", price: "38.0", description: "The Bambino Boheme Crystal Set is the perfect introduction to the Bohème Crystals. Use individually for a pure experience true to each type or mix them up for a truly ethereal bathing experience. Bohème Crystals conjure an bathing experience like never before with detoxifying salts + delicate petals. Submerge weekly into a bath of Bohème Crystals + warm water.", picture: "bath-salts.jpeg"}
])
